# Generated by Django 4.2.26 on 2025-11-16 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_album_subalbum_photo_album_photo_sub_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='map_location',
            field=models.ForeignKey(blank=True, help_text='Link to a predefined place on the map', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.maplocation'),
        ),
    ]
